// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TNArchives.sos.proto

#include "TNArchives.sos.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace TNSOS {
constexpr SheetStylePropertyChangeSetArchive::SheetStylePropertyChangeSetArchive(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : fill_(nullptr)
  , fill_undefined_(false){}
struct SheetStylePropertyChangeSetArchiveDefaultTypeInternal {
  constexpr SheetStylePropertyChangeSetArchiveDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~SheetStylePropertyChangeSetArchiveDefaultTypeInternal() {}
  union {
    SheetStylePropertyChangeSetArchive _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT SheetStylePropertyChangeSetArchiveDefaultTypeInternal _SheetStylePropertyChangeSetArchive_default_instance_;
}  // namespace TNSOS
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TNArchives_2esos_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_TNArchives_2esos_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TNArchives_2esos_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_TNArchives_2esos_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::TNSOS::SheetStylePropertyChangeSetArchive, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::TNSOS::SheetStylePropertyChangeSetArchive, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::TNSOS::SheetStylePropertyChangeSetArchive, fill_),
  PROTOBUF_FIELD_OFFSET(::TNSOS::SheetStylePropertyChangeSetArchive, fill_undefined_),
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::TNSOS::SheetStylePropertyChangeSetArchive)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::TNSOS::_SheetStylePropertyChangeSetArchive_default_instance_),
};

const char descriptor_table_protodef_TNArchives_2esos_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024TNArchives.sos.proto\022\005TNSOS\032\025TSDArchiv"
  "es.sos.proto\"c\n\"SheetStylePropertyChange"
  "SetArchive\022%\n\004fill\030\001 \001(\0132\027.TSDSOS.SpecFi"
  "llArchive\022\026\n\016fill_undefined\030\002 \001(\010"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_TNArchives_2esos_2eproto_deps[1] = {
  &::descriptor_table_TSDArchives_2esos_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TNArchives_2esos_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TNArchives_2esos_2eproto = {
  false, false, 153, descriptor_table_protodef_TNArchives_2esos_2eproto, "TNArchives.sos.proto", 
  &descriptor_table_TNArchives_2esos_2eproto_once, descriptor_table_TNArchives_2esos_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_TNArchives_2esos_2eproto::offsets,
  file_level_metadata_TNArchives_2esos_2eproto, file_level_enum_descriptors_TNArchives_2esos_2eproto, file_level_service_descriptors_TNArchives_2esos_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_TNArchives_2esos_2eproto_getter() {
  return &descriptor_table_TNArchives_2esos_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TNArchives_2esos_2eproto(&descriptor_table_TNArchives_2esos_2eproto);
namespace TNSOS {

// ===================================================================

class SheetStylePropertyChangeSetArchive::_Internal {
 public:
  using HasBits = decltype(std::declval<SheetStylePropertyChangeSetArchive>()._has_bits_);
  static const ::TSDSOS::SpecFillArchive& fill(const SheetStylePropertyChangeSetArchive* msg);
  static void set_has_fill(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_fill_undefined(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::TSDSOS::SpecFillArchive&
SheetStylePropertyChangeSetArchive::_Internal::fill(const SheetStylePropertyChangeSetArchive* msg) {
  return *msg->fill_;
}
void SheetStylePropertyChangeSetArchive::clear_fill() {
  if (fill_ != nullptr) fill_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
SheetStylePropertyChangeSetArchive::SheetStylePropertyChangeSetArchive(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:TNSOS.SheetStylePropertyChangeSetArchive)
}
SheetStylePropertyChangeSetArchive::SheetStylePropertyChangeSetArchive(const SheetStylePropertyChangeSetArchive& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_fill()) {
    fill_ = new ::TSDSOS::SpecFillArchive(*from.fill_);
  } else {
    fill_ = nullptr;
  }
  fill_undefined_ = from.fill_undefined_;
  // @@protoc_insertion_point(copy_constructor:TNSOS.SheetStylePropertyChangeSetArchive)
}

void SheetStylePropertyChangeSetArchive::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&fill_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&fill_undefined_) -
    reinterpret_cast<char*>(&fill_)) + sizeof(fill_undefined_));
}

SheetStylePropertyChangeSetArchive::~SheetStylePropertyChangeSetArchive() {
  // @@protoc_insertion_point(destructor:TNSOS.SheetStylePropertyChangeSetArchive)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SheetStylePropertyChangeSetArchive::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete fill_;
}

void SheetStylePropertyChangeSetArchive::ArenaDtor(void* object) {
  SheetStylePropertyChangeSetArchive* _this = reinterpret_cast< SheetStylePropertyChangeSetArchive* >(object);
  (void)_this;
}
void SheetStylePropertyChangeSetArchive::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SheetStylePropertyChangeSetArchive::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void SheetStylePropertyChangeSetArchive::Clear() {
// @@protoc_insertion_point(message_clear_start:TNSOS.SheetStylePropertyChangeSetArchive)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(fill_ != nullptr);
    fill_->Clear();
  }
  fill_undefined_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SheetStylePropertyChangeSetArchive::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .TSDSOS.SpecFillArchive fill = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_fill(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bool fill_undefined = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_fill_undefined(&has_bits);
          fill_undefined_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SheetStylePropertyChangeSetArchive::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TNSOS.SheetStylePropertyChangeSetArchive)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .TSDSOS.SpecFillArchive fill = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::fill(this), target, stream);
  }

  // optional bool fill_undefined = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_fill_undefined(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TNSOS.SheetStylePropertyChangeSetArchive)
  return target;
}

size_t SheetStylePropertyChangeSetArchive::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TNSOS.SheetStylePropertyChangeSetArchive)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional .TSDSOS.SpecFillArchive fill = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *fill_);
    }

    // optional bool fill_undefined = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SheetStylePropertyChangeSetArchive::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TNSOS.SheetStylePropertyChangeSetArchive)
  GOOGLE_DCHECK_NE(&from, this);
  const SheetStylePropertyChangeSetArchive* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SheetStylePropertyChangeSetArchive>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TNSOS.SheetStylePropertyChangeSetArchive)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TNSOS.SheetStylePropertyChangeSetArchive)
    MergeFrom(*source);
  }
}

void SheetStylePropertyChangeSetArchive::MergeFrom(const SheetStylePropertyChangeSetArchive& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TNSOS.SheetStylePropertyChangeSetArchive)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_fill()->::TSDSOS::SpecFillArchive::MergeFrom(from._internal_fill());
    }
    if (cached_has_bits & 0x00000002u) {
      fill_undefined_ = from.fill_undefined_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SheetStylePropertyChangeSetArchive::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TNSOS.SheetStylePropertyChangeSetArchive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SheetStylePropertyChangeSetArchive::CopyFrom(const SheetStylePropertyChangeSetArchive& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TNSOS.SheetStylePropertyChangeSetArchive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SheetStylePropertyChangeSetArchive::IsInitialized() const {
  if (_internal_has_fill()) {
    if (!fill_->IsInitialized()) return false;
  }
  return true;
}

void SheetStylePropertyChangeSetArchive::InternalSwap(SheetStylePropertyChangeSetArchive* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SheetStylePropertyChangeSetArchive, fill_undefined_)
      + sizeof(SheetStylePropertyChangeSetArchive::fill_undefined_)
      - PROTOBUF_FIELD_OFFSET(SheetStylePropertyChangeSetArchive, fill_)>(
          reinterpret_cast<char*>(&fill_),
          reinterpret_cast<char*>(&other->fill_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SheetStylePropertyChangeSetArchive::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TNArchives_2esos_2eproto_getter, &descriptor_table_TNArchives_2esos_2eproto_once,
      file_level_metadata_TNArchives_2esos_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace TNSOS
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TNSOS::SheetStylePropertyChangeSetArchive* Arena::CreateMaybeMessage< ::TNSOS::SheetStylePropertyChangeSetArchive >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TNSOS::SheetStylePropertyChangeSetArchive >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
