// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TPCommandArchives.sos.proto

#include "TPCommandArchives.sos.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace TPSOS {
constexpr InducedVerifyDocumentWithServerCommandArchive::InducedVerifyDocumentWithServerCommandArchive(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : drawables_z_order_list_()
  , super_(nullptr)
  , drawables_z_order_list_undefined_(false){}
struct InducedVerifyDocumentWithServerCommandArchiveDefaultTypeInternal {
  constexpr InducedVerifyDocumentWithServerCommandArchiveDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~InducedVerifyDocumentWithServerCommandArchiveDefaultTypeInternal() {}
  union {
    InducedVerifyDocumentWithServerCommandArchive _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT InducedVerifyDocumentWithServerCommandArchiveDefaultTypeInternal _InducedVerifyDocumentWithServerCommandArchive_default_instance_;
constexpr InducedVerifyDrawableZOrdersWithServerCommandArchive::InducedVerifyDrawableZOrdersWithServerCommandArchive(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : super_(nullptr){}
struct InducedVerifyDrawableZOrdersWithServerCommandArchiveDefaultTypeInternal {
  constexpr InducedVerifyDrawableZOrdersWithServerCommandArchiveDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~InducedVerifyDrawableZOrdersWithServerCommandArchiveDefaultTypeInternal() {}
  union {
    InducedVerifyDrawableZOrdersWithServerCommandArchive _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT InducedVerifyDrawableZOrdersWithServerCommandArchiveDefaultTypeInternal _InducedVerifyDrawableZOrdersWithServerCommandArchive_default_instance_;
constexpr ReapplyPageTemplateCommandArchive::ReapplyPageTemplateCommandArchive(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : super_(nullptr){}
struct ReapplyPageTemplateCommandArchiveDefaultTypeInternal {
  constexpr ReapplyPageTemplateCommandArchiveDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ReapplyPageTemplateCommandArchiveDefaultTypeInternal() {}
  union {
    ReapplyPageTemplateCommandArchive _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ReapplyPageTemplateCommandArchiveDefaultTypeInternal _ReapplyPageTemplateCommandArchive_default_instance_;
}  // namespace TPSOS
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_TPCommandArchives_2esos_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_TPCommandArchives_2esos_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_TPCommandArchives_2esos_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_TPCommandArchives_2esos_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::TPSOS::InducedVerifyDocumentWithServerCommandArchive, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::TPSOS::InducedVerifyDocumentWithServerCommandArchive, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::TPSOS::InducedVerifyDocumentWithServerCommandArchive, super_),
  PROTOBUF_FIELD_OFFSET(::TPSOS::InducedVerifyDocumentWithServerCommandArchive, drawables_z_order_list_),
  PROTOBUF_FIELD_OFFSET(::TPSOS::InducedVerifyDocumentWithServerCommandArchive, drawables_z_order_list_undefined_),
  0,
  ~0u,
  1,
  PROTOBUF_FIELD_OFFSET(::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive, super_),
  0,
  PROTOBUF_FIELD_OFFSET(::TPSOS::ReapplyPageTemplateCommandArchive, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::TPSOS::ReapplyPageTemplateCommandArchive, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::TPSOS::ReapplyPageTemplateCommandArchive, super_),
  0,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::TPSOS::InducedVerifyDocumentWithServerCommandArchive)},
  { 11, 17, sizeof(::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive)},
  { 18, 24, sizeof(::TPSOS::ReapplyPageTemplateCommandArchive)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::TPSOS::_InducedVerifyDocumentWithServerCommandArchive_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::TPSOS::_InducedVerifyDrawableZOrdersWithServerCommandArchive_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::TPSOS::_ReapplyPageTemplateCommandArchive_default_instance_),
};

const char descriptor_table_protodef_TPCommandArchives_2esos_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033TPCommandArchives.sos.proto\022\005TPSOS\032\034TS"
  "ACommandArchives.sos.proto\032\021TSKArchives."
  "proto\032\021TSPMessages.proto\"\250\001\n-InducedVeri"
  "fyDocumentWithServerCommandArchive\022\"\n\005su"
  "per\030\001 \002(\0132\023.TSK.CommandArchive\022)\n\026drawab"
  "les_z_order_list\030\002 \003(\0132\t.TSP.UUID\022(\n dra"
  "wables_z_order_list_undefined\030\003 \001(\010\"\203\001\n4"
  "InducedVerifyDrawableZOrdersWithServerCo"
  "mmandArchive\022K\n\005super\030\001 \002(\0132<.TSASOS.Ind"
  "ucedVerifyDrawableZOrdersWithServerComma"
  "ndArchive\"W\n!ReapplyPageTemplateCommandA"
  "rchive\0222\n\005super\030\001 \002(\0132#.TSASOS.CommandRe"
  "applyMasterArchive"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_TPCommandArchives_2esos_2eproto_deps[3] = {
  &::descriptor_table_TSACommandArchives_2esos_2eproto,
  &::descriptor_table_TSKArchives_2eproto,
  &::descriptor_table_TSPMessages_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_TPCommandArchives_2esos_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TPCommandArchives_2esos_2eproto = {
  false, false, 498, descriptor_table_protodef_TPCommandArchives_2esos_2eproto, "TPCommandArchives.sos.proto", 
  &descriptor_table_TPCommandArchives_2esos_2eproto_once, descriptor_table_TPCommandArchives_2esos_2eproto_deps, 3, 3,
  schemas, file_default_instances, TableStruct_TPCommandArchives_2esos_2eproto::offsets,
  file_level_metadata_TPCommandArchives_2esos_2eproto, file_level_enum_descriptors_TPCommandArchives_2esos_2eproto, file_level_service_descriptors_TPCommandArchives_2esos_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_TPCommandArchives_2esos_2eproto_getter() {
  return &descriptor_table_TPCommandArchives_2esos_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_TPCommandArchives_2esos_2eproto(&descriptor_table_TPCommandArchives_2esos_2eproto);
namespace TPSOS {

// ===================================================================

class InducedVerifyDocumentWithServerCommandArchive::_Internal {
 public:
  using HasBits = decltype(std::declval<InducedVerifyDocumentWithServerCommandArchive>()._has_bits_);
  static const ::TSK::CommandArchive& super(const InducedVerifyDocumentWithServerCommandArchive* msg);
  static void set_has_super(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_drawables_z_order_list_undefined(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::TSK::CommandArchive&
InducedVerifyDocumentWithServerCommandArchive::_Internal::super(const InducedVerifyDocumentWithServerCommandArchive* msg) {
  return *msg->super_;
}
void InducedVerifyDocumentWithServerCommandArchive::clear_super() {
  if (super_ != nullptr) super_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
void InducedVerifyDocumentWithServerCommandArchive::clear_drawables_z_order_list() {
  drawables_z_order_list_.Clear();
}
InducedVerifyDocumentWithServerCommandArchive::InducedVerifyDocumentWithServerCommandArchive(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  drawables_z_order_list_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
}
InducedVerifyDocumentWithServerCommandArchive::InducedVerifyDocumentWithServerCommandArchive(const InducedVerifyDocumentWithServerCommandArchive& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      drawables_z_order_list_(from.drawables_z_order_list_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_super()) {
    super_ = new ::TSK::CommandArchive(*from.super_);
  } else {
    super_ = nullptr;
  }
  drawables_z_order_list_undefined_ = from.drawables_z_order_list_undefined_;
  // @@protoc_insertion_point(copy_constructor:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
}

void InducedVerifyDocumentWithServerCommandArchive::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&super_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&drawables_z_order_list_undefined_) -
    reinterpret_cast<char*>(&super_)) + sizeof(drawables_z_order_list_undefined_));
}

InducedVerifyDocumentWithServerCommandArchive::~InducedVerifyDocumentWithServerCommandArchive() {
  // @@protoc_insertion_point(destructor:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void InducedVerifyDocumentWithServerCommandArchive::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete super_;
}

void InducedVerifyDocumentWithServerCommandArchive::ArenaDtor(void* object) {
  InducedVerifyDocumentWithServerCommandArchive* _this = reinterpret_cast< InducedVerifyDocumentWithServerCommandArchive* >(object);
  (void)_this;
}
void InducedVerifyDocumentWithServerCommandArchive::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void InducedVerifyDocumentWithServerCommandArchive::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InducedVerifyDocumentWithServerCommandArchive::Clear() {
// @@protoc_insertion_point(message_clear_start:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  drawables_z_order_list_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(super_ != nullptr);
    super_->Clear();
  }
  drawables_z_order_list_undefined_ = false;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InducedVerifyDocumentWithServerCommandArchive::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .TSK.CommandArchive super = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_super(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .TSP.UUID drawables_z_order_list = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_drawables_z_order_list(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // optional bool drawables_z_order_list_undefined = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _Internal::set_has_drawables_z_order_list_undefined(&has_bits);
          drawables_z_order_list_undefined_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* InducedVerifyDocumentWithServerCommandArchive::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TSK.CommandArchive super = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::super(this), target, stream);
  }

  // repeated .TSP.UUID drawables_z_order_list = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_drawables_z_order_list_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_drawables_z_order_list(i), target, stream);
  }

  // optional bool drawables_z_order_list_undefined = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_drawables_z_order_list_undefined(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  return target;
}

size_t InducedVerifyDocumentWithServerCommandArchive::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  size_t total_size = 0;

  // required .TSK.CommandArchive super = 1;
  if (_internal_has_super()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *super_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .TSP.UUID drawables_z_order_list = 2;
  total_size += 1UL * this->_internal_drawables_z_order_list_size();
  for (const auto& msg : this->drawables_z_order_list_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional bool drawables_z_order_list_undefined = 3;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000002u) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InducedVerifyDocumentWithServerCommandArchive::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  GOOGLE_DCHECK_NE(&from, this);
  const InducedVerifyDocumentWithServerCommandArchive* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<InducedVerifyDocumentWithServerCommandArchive>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
    MergeFrom(*source);
  }
}

void InducedVerifyDocumentWithServerCommandArchive::MergeFrom(const InducedVerifyDocumentWithServerCommandArchive& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  drawables_z_order_list_.MergeFrom(from.drawables_z_order_list_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_super()->::TSK::CommandArchive::MergeFrom(from._internal_super());
    }
    if (cached_has_bits & 0x00000002u) {
      drawables_z_order_list_undefined_ = from.drawables_z_order_list_undefined_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void InducedVerifyDocumentWithServerCommandArchive::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InducedVerifyDocumentWithServerCommandArchive::CopyFrom(const InducedVerifyDocumentWithServerCommandArchive& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InducedVerifyDocumentWithServerCommandArchive::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(drawables_z_order_list_)) return false;
  if (_internal_has_super()) {
    if (!super_->IsInitialized()) return false;
  }
  return true;
}

void InducedVerifyDocumentWithServerCommandArchive::InternalSwap(InducedVerifyDocumentWithServerCommandArchive* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  drawables_z_order_list_.InternalSwap(&other->drawables_z_order_list_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InducedVerifyDocumentWithServerCommandArchive, drawables_z_order_list_undefined_)
      + sizeof(InducedVerifyDocumentWithServerCommandArchive::drawables_z_order_list_undefined_)
      - PROTOBUF_FIELD_OFFSET(InducedVerifyDocumentWithServerCommandArchive, super_)>(
          reinterpret_cast<char*>(&super_),
          reinterpret_cast<char*>(&other->super_));
}

::PROTOBUF_NAMESPACE_ID::Metadata InducedVerifyDocumentWithServerCommandArchive::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TPCommandArchives_2esos_2eproto_getter, &descriptor_table_TPCommandArchives_2esos_2eproto_once,
      file_level_metadata_TPCommandArchives_2esos_2eproto[0]);
}

// ===================================================================

class InducedVerifyDrawableZOrdersWithServerCommandArchive::_Internal {
 public:
  using HasBits = decltype(std::declval<InducedVerifyDrawableZOrdersWithServerCommandArchive>()._has_bits_);
  static const ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive& super(const InducedVerifyDrawableZOrdersWithServerCommandArchive* msg);
  static void set_has_super(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive&
InducedVerifyDrawableZOrdersWithServerCommandArchive::_Internal::super(const InducedVerifyDrawableZOrdersWithServerCommandArchive* msg) {
  return *msg->super_;
}
void InducedVerifyDrawableZOrdersWithServerCommandArchive::clear_super() {
  if (super_ != nullptr) super_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
InducedVerifyDrawableZOrdersWithServerCommandArchive::InducedVerifyDrawableZOrdersWithServerCommandArchive(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
}
InducedVerifyDrawableZOrdersWithServerCommandArchive::InducedVerifyDrawableZOrdersWithServerCommandArchive(const InducedVerifyDrawableZOrdersWithServerCommandArchive& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_super()) {
    super_ = new ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive(*from.super_);
  } else {
    super_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::SharedCtor() {
super_ = nullptr;
}

InducedVerifyDrawableZOrdersWithServerCommandArchive::~InducedVerifyDrawableZOrdersWithServerCommandArchive() {
  // @@protoc_insertion_point(destructor:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete super_;
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::ArenaDtor(void* object) {
  InducedVerifyDrawableZOrdersWithServerCommandArchive* _this = reinterpret_cast< InducedVerifyDrawableZOrdersWithServerCommandArchive* >(object);
  (void)_this;
}
void InducedVerifyDrawableZOrdersWithServerCommandArchive::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void InducedVerifyDrawableZOrdersWithServerCommandArchive::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::Clear() {
// @@protoc_insertion_point(message_clear_start:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(super_ != nullptr);
    super_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InducedVerifyDrawableZOrdersWithServerCommandArchive::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .TSASOS.InducedVerifyDrawableZOrdersWithServerCommandArchive super = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_super(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* InducedVerifyDrawableZOrdersWithServerCommandArchive::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TSASOS.InducedVerifyDrawableZOrdersWithServerCommandArchive super = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::super(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  return target;
}

size_t InducedVerifyDrawableZOrdersWithServerCommandArchive::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  size_t total_size = 0;

  // required .TSASOS.InducedVerifyDrawableZOrdersWithServerCommandArchive super = 1;
  if (_internal_has_super()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *super_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  GOOGLE_DCHECK_NE(&from, this);
  const InducedVerifyDrawableZOrdersWithServerCommandArchive* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<InducedVerifyDrawableZOrdersWithServerCommandArchive>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
    MergeFrom(*source);
  }
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::MergeFrom(const InducedVerifyDrawableZOrdersWithServerCommandArchive& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_super()) {
    _internal_mutable_super()->::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive::MergeFrom(from._internal_super());
  }
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::CopyFrom(const InducedVerifyDrawableZOrdersWithServerCommandArchive& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InducedVerifyDrawableZOrdersWithServerCommandArchive::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_super()) {
    if (!super_->IsInitialized()) return false;
  }
  return true;
}

void InducedVerifyDrawableZOrdersWithServerCommandArchive::InternalSwap(InducedVerifyDrawableZOrdersWithServerCommandArchive* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(super_, other->super_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InducedVerifyDrawableZOrdersWithServerCommandArchive::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TPCommandArchives_2esos_2eproto_getter, &descriptor_table_TPCommandArchives_2esos_2eproto_once,
      file_level_metadata_TPCommandArchives_2esos_2eproto[1]);
}

// ===================================================================

class ReapplyPageTemplateCommandArchive::_Internal {
 public:
  using HasBits = decltype(std::declval<ReapplyPageTemplateCommandArchive>()._has_bits_);
  static const ::TSASOS::CommandReapplyMasterArchive& super(const ReapplyPageTemplateCommandArchive* msg);
  static void set_has_super(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

const ::TSASOS::CommandReapplyMasterArchive&
ReapplyPageTemplateCommandArchive::_Internal::super(const ReapplyPageTemplateCommandArchive* msg) {
  return *msg->super_;
}
void ReapplyPageTemplateCommandArchive::clear_super() {
  if (super_ != nullptr) super_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
ReapplyPageTemplateCommandArchive::ReapplyPageTemplateCommandArchive(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:TPSOS.ReapplyPageTemplateCommandArchive)
}
ReapplyPageTemplateCommandArchive::ReapplyPageTemplateCommandArchive(const ReapplyPageTemplateCommandArchive& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_super()) {
    super_ = new ::TSASOS::CommandReapplyMasterArchive(*from.super_);
  } else {
    super_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:TPSOS.ReapplyPageTemplateCommandArchive)
}

void ReapplyPageTemplateCommandArchive::SharedCtor() {
super_ = nullptr;
}

ReapplyPageTemplateCommandArchive::~ReapplyPageTemplateCommandArchive() {
  // @@protoc_insertion_point(destructor:TPSOS.ReapplyPageTemplateCommandArchive)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReapplyPageTemplateCommandArchive::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete super_;
}

void ReapplyPageTemplateCommandArchive::ArenaDtor(void* object) {
  ReapplyPageTemplateCommandArchive* _this = reinterpret_cast< ReapplyPageTemplateCommandArchive* >(object);
  (void)_this;
}
void ReapplyPageTemplateCommandArchive::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReapplyPageTemplateCommandArchive::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReapplyPageTemplateCommandArchive::Clear() {
// @@protoc_insertion_point(message_clear_start:TPSOS.ReapplyPageTemplateCommandArchive)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(super_ != nullptr);
    super_->Clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReapplyPageTemplateCommandArchive::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required .TSASOS.CommandReapplyMasterArchive super = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_super(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReapplyPageTemplateCommandArchive::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TPSOS.ReapplyPageTemplateCommandArchive)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .TSASOS.CommandReapplyMasterArchive super = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::super(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TPSOS.ReapplyPageTemplateCommandArchive)
  return target;
}

size_t ReapplyPageTemplateCommandArchive::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TPSOS.ReapplyPageTemplateCommandArchive)
  size_t total_size = 0;

  // required .TSASOS.CommandReapplyMasterArchive super = 1;
  if (_internal_has_super()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *super_);
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReapplyPageTemplateCommandArchive::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TPSOS.ReapplyPageTemplateCommandArchive)
  GOOGLE_DCHECK_NE(&from, this);
  const ReapplyPageTemplateCommandArchive* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReapplyPageTemplateCommandArchive>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TPSOS.ReapplyPageTemplateCommandArchive)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TPSOS.ReapplyPageTemplateCommandArchive)
    MergeFrom(*source);
  }
}

void ReapplyPageTemplateCommandArchive::MergeFrom(const ReapplyPageTemplateCommandArchive& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TPSOS.ReapplyPageTemplateCommandArchive)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_super()) {
    _internal_mutable_super()->::TSASOS::CommandReapplyMasterArchive::MergeFrom(from._internal_super());
  }
}

void ReapplyPageTemplateCommandArchive::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TPSOS.ReapplyPageTemplateCommandArchive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReapplyPageTemplateCommandArchive::CopyFrom(const ReapplyPageTemplateCommandArchive& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TPSOS.ReapplyPageTemplateCommandArchive)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReapplyPageTemplateCommandArchive::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_super()) {
    if (!super_->IsInitialized()) return false;
  }
  return true;
}

void ReapplyPageTemplateCommandArchive::InternalSwap(ReapplyPageTemplateCommandArchive* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  swap(super_, other->super_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ReapplyPageTemplateCommandArchive::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_TPCommandArchives_2esos_2eproto_getter, &descriptor_table_TPCommandArchives_2esos_2eproto_once,
      file_level_metadata_TPCommandArchives_2esos_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace TPSOS
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TPSOS::InducedVerifyDocumentWithServerCommandArchive* Arena::CreateMaybeMessage< ::TPSOS::InducedVerifyDocumentWithServerCommandArchive >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TPSOS::InducedVerifyDocumentWithServerCommandArchive >(arena);
}
template<> PROTOBUF_NOINLINE ::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* Arena::CreateMaybeMessage< ::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive >(arena);
}
template<> PROTOBUF_NOINLINE ::TPSOS::ReapplyPageTemplateCommandArchive* Arena::CreateMaybeMessage< ::TPSOS::ReapplyPageTemplateCommandArchive >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TPSOS::ReapplyPageTemplateCommandArchive >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
