// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TPCommandArchives.sos.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_TPCommandArchives_2esos_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_TPCommandArchives_2esos_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "TSACommandArchives.sos.pb.h"
#include "TSKArchives.pb.h"
#include "TSPMessages.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_TPCommandArchives_2esos_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_TPCommandArchives_2esos_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_TPCommandArchives_2esos_2eproto;
namespace TPSOS {
class InducedVerifyDocumentWithServerCommandArchive;
struct InducedVerifyDocumentWithServerCommandArchiveDefaultTypeInternal;
extern InducedVerifyDocumentWithServerCommandArchiveDefaultTypeInternal _InducedVerifyDocumentWithServerCommandArchive_default_instance_;
class InducedVerifyDrawableZOrdersWithServerCommandArchive;
struct InducedVerifyDrawableZOrdersWithServerCommandArchiveDefaultTypeInternal;
extern InducedVerifyDrawableZOrdersWithServerCommandArchiveDefaultTypeInternal _InducedVerifyDrawableZOrdersWithServerCommandArchive_default_instance_;
class ReapplyPageTemplateCommandArchive;
struct ReapplyPageTemplateCommandArchiveDefaultTypeInternal;
extern ReapplyPageTemplateCommandArchiveDefaultTypeInternal _ReapplyPageTemplateCommandArchive_default_instance_;
}  // namespace TPSOS
PROTOBUF_NAMESPACE_OPEN
template<> ::TPSOS::InducedVerifyDocumentWithServerCommandArchive* Arena::CreateMaybeMessage<::TPSOS::InducedVerifyDocumentWithServerCommandArchive>(Arena*);
template<> ::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* Arena::CreateMaybeMessage<::TPSOS::InducedVerifyDrawableZOrdersWithServerCommandArchive>(Arena*);
template<> ::TPSOS::ReapplyPageTemplateCommandArchive* Arena::CreateMaybeMessage<::TPSOS::ReapplyPageTemplateCommandArchive>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace TPSOS {

// ===================================================================

class InducedVerifyDocumentWithServerCommandArchive PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TPSOS.InducedVerifyDocumentWithServerCommandArchive) */ {
 public:
  inline InducedVerifyDocumentWithServerCommandArchive() : InducedVerifyDocumentWithServerCommandArchive(nullptr) {}
  ~InducedVerifyDocumentWithServerCommandArchive() override;
  explicit constexpr InducedVerifyDocumentWithServerCommandArchive(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InducedVerifyDocumentWithServerCommandArchive(const InducedVerifyDocumentWithServerCommandArchive& from);
  InducedVerifyDocumentWithServerCommandArchive(InducedVerifyDocumentWithServerCommandArchive&& from) noexcept
    : InducedVerifyDocumentWithServerCommandArchive() {
    *this = ::std::move(from);
  }

  inline InducedVerifyDocumentWithServerCommandArchive& operator=(const InducedVerifyDocumentWithServerCommandArchive& from) {
    CopyFrom(from);
    return *this;
  }
  inline InducedVerifyDocumentWithServerCommandArchive& operator=(InducedVerifyDocumentWithServerCommandArchive&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InducedVerifyDocumentWithServerCommandArchive& default_instance() {
    return *internal_default_instance();
  }
  static inline const InducedVerifyDocumentWithServerCommandArchive* internal_default_instance() {
    return reinterpret_cast<const InducedVerifyDocumentWithServerCommandArchive*>(
               &_InducedVerifyDocumentWithServerCommandArchive_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InducedVerifyDocumentWithServerCommandArchive& a, InducedVerifyDocumentWithServerCommandArchive& b) {
    a.Swap(&b);
  }
  inline void Swap(InducedVerifyDocumentWithServerCommandArchive* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InducedVerifyDocumentWithServerCommandArchive* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InducedVerifyDocumentWithServerCommandArchive* New() const final {
    return CreateMaybeMessage<InducedVerifyDocumentWithServerCommandArchive>(nullptr);
  }

  InducedVerifyDocumentWithServerCommandArchive* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InducedVerifyDocumentWithServerCommandArchive>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InducedVerifyDocumentWithServerCommandArchive& from);
  void MergeFrom(const InducedVerifyDocumentWithServerCommandArchive& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InducedVerifyDocumentWithServerCommandArchive* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TPSOS.InducedVerifyDocumentWithServerCommandArchive";
  }
  protected:
  explicit InducedVerifyDocumentWithServerCommandArchive(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDrawablesZOrderListFieldNumber = 2,
    kSuperFieldNumber = 1,
    kDrawablesZOrderListUndefinedFieldNumber = 3,
  };
  // repeated .TSP.UUID drawables_z_order_list = 2;
  int drawables_z_order_list_size() const;
  private:
  int _internal_drawables_z_order_list_size() const;
  public:
  void clear_drawables_z_order_list();
  ::TSP::UUID* mutable_drawables_z_order_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TSP::UUID >*
      mutable_drawables_z_order_list();
  private:
  const ::TSP::UUID& _internal_drawables_z_order_list(int index) const;
  ::TSP::UUID* _internal_add_drawables_z_order_list();
  public:
  const ::TSP::UUID& drawables_z_order_list(int index) const;
  ::TSP::UUID* add_drawables_z_order_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TSP::UUID >&
      drawables_z_order_list() const;

  // required .TSK.CommandArchive super = 1;
  bool has_super() const;
  private:
  bool _internal_has_super() const;
  public:
  void clear_super();
  const ::TSK::CommandArchive& super() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::TSK::CommandArchive* release_super();
  ::TSK::CommandArchive* mutable_super();
  void set_allocated_super(::TSK::CommandArchive* super);
  private:
  const ::TSK::CommandArchive& _internal_super() const;
  ::TSK::CommandArchive* _internal_mutable_super();
  public:
  void unsafe_arena_set_allocated_super(
      ::TSK::CommandArchive* super);
  ::TSK::CommandArchive* unsafe_arena_release_super();

  // optional bool drawables_z_order_list_undefined = 3;
  bool has_drawables_z_order_list_undefined() const;
  private:
  bool _internal_has_drawables_z_order_list_undefined() const;
  public:
  void clear_drawables_z_order_list_undefined();
  bool drawables_z_order_list_undefined() const;
  void set_drawables_z_order_list_undefined(bool value);
  private:
  bool _internal_drawables_z_order_list_undefined() const;
  void _internal_set_drawables_z_order_list_undefined(bool value);
  public:

  // @@protoc_insertion_point(class_scope:TPSOS.InducedVerifyDocumentWithServerCommandArchive)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TSP::UUID > drawables_z_order_list_;
  ::TSK::CommandArchive* super_;
  bool drawables_z_order_list_undefined_;
  friend struct ::TableStruct_TPCommandArchives_2esos_2eproto;
};
// -------------------------------------------------------------------

class InducedVerifyDrawableZOrdersWithServerCommandArchive PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive) */ {
 public:
  inline InducedVerifyDrawableZOrdersWithServerCommandArchive() : InducedVerifyDrawableZOrdersWithServerCommandArchive(nullptr) {}
  ~InducedVerifyDrawableZOrdersWithServerCommandArchive() override;
  explicit constexpr InducedVerifyDrawableZOrdersWithServerCommandArchive(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InducedVerifyDrawableZOrdersWithServerCommandArchive(const InducedVerifyDrawableZOrdersWithServerCommandArchive& from);
  InducedVerifyDrawableZOrdersWithServerCommandArchive(InducedVerifyDrawableZOrdersWithServerCommandArchive&& from) noexcept
    : InducedVerifyDrawableZOrdersWithServerCommandArchive() {
    *this = ::std::move(from);
  }

  inline InducedVerifyDrawableZOrdersWithServerCommandArchive& operator=(const InducedVerifyDrawableZOrdersWithServerCommandArchive& from) {
    CopyFrom(from);
    return *this;
  }
  inline InducedVerifyDrawableZOrdersWithServerCommandArchive& operator=(InducedVerifyDrawableZOrdersWithServerCommandArchive&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InducedVerifyDrawableZOrdersWithServerCommandArchive& default_instance() {
    return *internal_default_instance();
  }
  static inline const InducedVerifyDrawableZOrdersWithServerCommandArchive* internal_default_instance() {
    return reinterpret_cast<const InducedVerifyDrawableZOrdersWithServerCommandArchive*>(
               &_InducedVerifyDrawableZOrdersWithServerCommandArchive_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InducedVerifyDrawableZOrdersWithServerCommandArchive& a, InducedVerifyDrawableZOrdersWithServerCommandArchive& b) {
    a.Swap(&b);
  }
  inline void Swap(InducedVerifyDrawableZOrdersWithServerCommandArchive* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InducedVerifyDrawableZOrdersWithServerCommandArchive* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InducedVerifyDrawableZOrdersWithServerCommandArchive* New() const final {
    return CreateMaybeMessage<InducedVerifyDrawableZOrdersWithServerCommandArchive>(nullptr);
  }

  InducedVerifyDrawableZOrdersWithServerCommandArchive* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InducedVerifyDrawableZOrdersWithServerCommandArchive>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InducedVerifyDrawableZOrdersWithServerCommandArchive& from);
  void MergeFrom(const InducedVerifyDrawableZOrdersWithServerCommandArchive& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InducedVerifyDrawableZOrdersWithServerCommandArchive* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive";
  }
  protected:
  explicit InducedVerifyDrawableZOrdersWithServerCommandArchive(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuperFieldNumber = 1,
  };
  // required .TSASOS.InducedVerifyDrawableZOrdersWithServerCommandArchive super = 1;
  bool has_super() const;
  private:
  bool _internal_has_super() const;
  public:
  void clear_super();
  const ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive& super() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* release_super();
  ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* mutable_super();
  void set_allocated_super(::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* super);
  private:
  const ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive& _internal_super() const;
  ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* _internal_mutable_super();
  public:
  void unsafe_arena_set_allocated_super(
      ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* super);
  ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* unsafe_arena_release_super();

  // @@protoc_insertion_point(class_scope:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* super_;
  friend struct ::TableStruct_TPCommandArchives_2esos_2eproto;
};
// -------------------------------------------------------------------

class ReapplyPageTemplateCommandArchive PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TPSOS.ReapplyPageTemplateCommandArchive) */ {
 public:
  inline ReapplyPageTemplateCommandArchive() : ReapplyPageTemplateCommandArchive(nullptr) {}
  ~ReapplyPageTemplateCommandArchive() override;
  explicit constexpr ReapplyPageTemplateCommandArchive(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReapplyPageTemplateCommandArchive(const ReapplyPageTemplateCommandArchive& from);
  ReapplyPageTemplateCommandArchive(ReapplyPageTemplateCommandArchive&& from) noexcept
    : ReapplyPageTemplateCommandArchive() {
    *this = ::std::move(from);
  }

  inline ReapplyPageTemplateCommandArchive& operator=(const ReapplyPageTemplateCommandArchive& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReapplyPageTemplateCommandArchive& operator=(ReapplyPageTemplateCommandArchive&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReapplyPageTemplateCommandArchive& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReapplyPageTemplateCommandArchive* internal_default_instance() {
    return reinterpret_cast<const ReapplyPageTemplateCommandArchive*>(
               &_ReapplyPageTemplateCommandArchive_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ReapplyPageTemplateCommandArchive& a, ReapplyPageTemplateCommandArchive& b) {
    a.Swap(&b);
  }
  inline void Swap(ReapplyPageTemplateCommandArchive* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReapplyPageTemplateCommandArchive* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReapplyPageTemplateCommandArchive* New() const final {
    return CreateMaybeMessage<ReapplyPageTemplateCommandArchive>(nullptr);
  }

  ReapplyPageTemplateCommandArchive* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReapplyPageTemplateCommandArchive>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReapplyPageTemplateCommandArchive& from);
  void MergeFrom(const ReapplyPageTemplateCommandArchive& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReapplyPageTemplateCommandArchive* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TPSOS.ReapplyPageTemplateCommandArchive";
  }
  protected:
  explicit ReapplyPageTemplateCommandArchive(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSuperFieldNumber = 1,
  };
  // required .TSASOS.CommandReapplyMasterArchive super = 1;
  bool has_super() const;
  private:
  bool _internal_has_super() const;
  public:
  void clear_super();
  const ::TSASOS::CommandReapplyMasterArchive& super() const;
  PROTOBUF_FUTURE_MUST_USE_RESULT ::TSASOS::CommandReapplyMasterArchive* release_super();
  ::TSASOS::CommandReapplyMasterArchive* mutable_super();
  void set_allocated_super(::TSASOS::CommandReapplyMasterArchive* super);
  private:
  const ::TSASOS::CommandReapplyMasterArchive& _internal_super() const;
  ::TSASOS::CommandReapplyMasterArchive* _internal_mutable_super();
  public:
  void unsafe_arena_set_allocated_super(
      ::TSASOS::CommandReapplyMasterArchive* super);
  ::TSASOS::CommandReapplyMasterArchive* unsafe_arena_release_super();

  // @@protoc_insertion_point(class_scope:TPSOS.ReapplyPageTemplateCommandArchive)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::TSASOS::CommandReapplyMasterArchive* super_;
  friend struct ::TableStruct_TPCommandArchives_2esos_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InducedVerifyDocumentWithServerCommandArchive

// required .TSK.CommandArchive super = 1;
inline bool InducedVerifyDocumentWithServerCommandArchive::_internal_has_super() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || super_ != nullptr);
  return value;
}
inline bool InducedVerifyDocumentWithServerCommandArchive::has_super() const {
  return _internal_has_super();
}
inline const ::TSK::CommandArchive& InducedVerifyDocumentWithServerCommandArchive::_internal_super() const {
  const ::TSK::CommandArchive* p = super_;
  return p != nullptr ? *p : reinterpret_cast<const ::TSK::CommandArchive&>(
      ::TSK::_CommandArchive_default_instance_);
}
inline const ::TSK::CommandArchive& InducedVerifyDocumentWithServerCommandArchive::super() const {
  // @@protoc_insertion_point(field_get:TPSOS.InducedVerifyDocumentWithServerCommandArchive.super)
  return _internal_super();
}
inline void InducedVerifyDocumentWithServerCommandArchive::unsafe_arena_set_allocated_super(
    ::TSK::CommandArchive* super) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(super_);
  }
  super_ = super;
  if (super) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TPSOS.InducedVerifyDocumentWithServerCommandArchive.super)
}
inline ::TSK::CommandArchive* InducedVerifyDocumentWithServerCommandArchive::release_super() {
  _has_bits_[0] &= ~0x00000001u;
  ::TSK::CommandArchive* temp = super_;
  super_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::TSK::CommandArchive* InducedVerifyDocumentWithServerCommandArchive::unsafe_arena_release_super() {
  // @@protoc_insertion_point(field_release:TPSOS.InducedVerifyDocumentWithServerCommandArchive.super)
  _has_bits_[0] &= ~0x00000001u;
  ::TSK::CommandArchive* temp = super_;
  super_ = nullptr;
  return temp;
}
inline ::TSK::CommandArchive* InducedVerifyDocumentWithServerCommandArchive::_internal_mutable_super() {
  _has_bits_[0] |= 0x00000001u;
  if (super_ == nullptr) {
    auto* p = CreateMaybeMessage<::TSK::CommandArchive>(GetArena());
    super_ = p;
  }
  return super_;
}
inline ::TSK::CommandArchive* InducedVerifyDocumentWithServerCommandArchive::mutable_super() {
  // @@protoc_insertion_point(field_mutable:TPSOS.InducedVerifyDocumentWithServerCommandArchive.super)
  return _internal_mutable_super();
}
inline void InducedVerifyDocumentWithServerCommandArchive::set_allocated_super(::TSK::CommandArchive* super) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(super_);
  }
  if (super) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(super)->GetArena();
    if (message_arena != submessage_arena) {
      super = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, super, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  super_ = super;
  // @@protoc_insertion_point(field_set_allocated:TPSOS.InducedVerifyDocumentWithServerCommandArchive.super)
}

// repeated .TSP.UUID drawables_z_order_list = 2;
inline int InducedVerifyDocumentWithServerCommandArchive::_internal_drawables_z_order_list_size() const {
  return drawables_z_order_list_.size();
}
inline int InducedVerifyDocumentWithServerCommandArchive::drawables_z_order_list_size() const {
  return _internal_drawables_z_order_list_size();
}
inline ::TSP::UUID* InducedVerifyDocumentWithServerCommandArchive::mutable_drawables_z_order_list(int index) {
  // @@protoc_insertion_point(field_mutable:TPSOS.InducedVerifyDocumentWithServerCommandArchive.drawables_z_order_list)
  return drawables_z_order_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TSP::UUID >*
InducedVerifyDocumentWithServerCommandArchive::mutable_drawables_z_order_list() {
  // @@protoc_insertion_point(field_mutable_list:TPSOS.InducedVerifyDocumentWithServerCommandArchive.drawables_z_order_list)
  return &drawables_z_order_list_;
}
inline const ::TSP::UUID& InducedVerifyDocumentWithServerCommandArchive::_internal_drawables_z_order_list(int index) const {
  return drawables_z_order_list_.Get(index);
}
inline const ::TSP::UUID& InducedVerifyDocumentWithServerCommandArchive::drawables_z_order_list(int index) const {
  // @@protoc_insertion_point(field_get:TPSOS.InducedVerifyDocumentWithServerCommandArchive.drawables_z_order_list)
  return _internal_drawables_z_order_list(index);
}
inline ::TSP::UUID* InducedVerifyDocumentWithServerCommandArchive::_internal_add_drawables_z_order_list() {
  return drawables_z_order_list_.Add();
}
inline ::TSP::UUID* InducedVerifyDocumentWithServerCommandArchive::add_drawables_z_order_list() {
  // @@protoc_insertion_point(field_add:TPSOS.InducedVerifyDocumentWithServerCommandArchive.drawables_z_order_list)
  return _internal_add_drawables_z_order_list();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::TSP::UUID >&
InducedVerifyDocumentWithServerCommandArchive::drawables_z_order_list() const {
  // @@protoc_insertion_point(field_list:TPSOS.InducedVerifyDocumentWithServerCommandArchive.drawables_z_order_list)
  return drawables_z_order_list_;
}

// optional bool drawables_z_order_list_undefined = 3;
inline bool InducedVerifyDocumentWithServerCommandArchive::_internal_has_drawables_z_order_list_undefined() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool InducedVerifyDocumentWithServerCommandArchive::has_drawables_z_order_list_undefined() const {
  return _internal_has_drawables_z_order_list_undefined();
}
inline void InducedVerifyDocumentWithServerCommandArchive::clear_drawables_z_order_list_undefined() {
  drawables_z_order_list_undefined_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool InducedVerifyDocumentWithServerCommandArchive::_internal_drawables_z_order_list_undefined() const {
  return drawables_z_order_list_undefined_;
}
inline bool InducedVerifyDocumentWithServerCommandArchive::drawables_z_order_list_undefined() const {
  // @@protoc_insertion_point(field_get:TPSOS.InducedVerifyDocumentWithServerCommandArchive.drawables_z_order_list_undefined)
  return _internal_drawables_z_order_list_undefined();
}
inline void InducedVerifyDocumentWithServerCommandArchive::_internal_set_drawables_z_order_list_undefined(bool value) {
  _has_bits_[0] |= 0x00000002u;
  drawables_z_order_list_undefined_ = value;
}
inline void InducedVerifyDocumentWithServerCommandArchive::set_drawables_z_order_list_undefined(bool value) {
  _internal_set_drawables_z_order_list_undefined(value);
  // @@protoc_insertion_point(field_set:TPSOS.InducedVerifyDocumentWithServerCommandArchive.drawables_z_order_list_undefined)
}

// -------------------------------------------------------------------

// InducedVerifyDrawableZOrdersWithServerCommandArchive

// required .TSASOS.InducedVerifyDrawableZOrdersWithServerCommandArchive super = 1;
inline bool InducedVerifyDrawableZOrdersWithServerCommandArchive::_internal_has_super() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || super_ != nullptr);
  return value;
}
inline bool InducedVerifyDrawableZOrdersWithServerCommandArchive::has_super() const {
  return _internal_has_super();
}
inline const ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive& InducedVerifyDrawableZOrdersWithServerCommandArchive::_internal_super() const {
  const ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* p = super_;
  return p != nullptr ? *p : reinterpret_cast<const ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive&>(
      ::TSASOS::_InducedVerifyDrawableZOrdersWithServerCommandArchive_default_instance_);
}
inline const ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive& InducedVerifyDrawableZOrdersWithServerCommandArchive::super() const {
  // @@protoc_insertion_point(field_get:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive.super)
  return _internal_super();
}
inline void InducedVerifyDrawableZOrdersWithServerCommandArchive::unsafe_arena_set_allocated_super(
    ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* super) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(super_);
  }
  super_ = super;
  if (super) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive.super)
}
inline ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* InducedVerifyDrawableZOrdersWithServerCommandArchive::release_super() {
  _has_bits_[0] &= ~0x00000001u;
  ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* temp = super_;
  super_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* InducedVerifyDrawableZOrdersWithServerCommandArchive::unsafe_arena_release_super() {
  // @@protoc_insertion_point(field_release:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive.super)
  _has_bits_[0] &= ~0x00000001u;
  ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* temp = super_;
  super_ = nullptr;
  return temp;
}
inline ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* InducedVerifyDrawableZOrdersWithServerCommandArchive::_internal_mutable_super() {
  _has_bits_[0] |= 0x00000001u;
  if (super_ == nullptr) {
    auto* p = CreateMaybeMessage<::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive>(GetArena());
    super_ = p;
  }
  return super_;
}
inline ::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* InducedVerifyDrawableZOrdersWithServerCommandArchive::mutable_super() {
  // @@protoc_insertion_point(field_mutable:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive.super)
  return _internal_mutable_super();
}
inline void InducedVerifyDrawableZOrdersWithServerCommandArchive::set_allocated_super(::TSASOS::InducedVerifyDrawableZOrdersWithServerCommandArchive* super) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(super_);
  }
  if (super) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(super)->GetArena();
    if (message_arena != submessage_arena) {
      super = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, super, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  super_ = super;
  // @@protoc_insertion_point(field_set_allocated:TPSOS.InducedVerifyDrawableZOrdersWithServerCommandArchive.super)
}

// -------------------------------------------------------------------

// ReapplyPageTemplateCommandArchive

// required .TSASOS.CommandReapplyMasterArchive super = 1;
inline bool ReapplyPageTemplateCommandArchive::_internal_has_super() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || super_ != nullptr);
  return value;
}
inline bool ReapplyPageTemplateCommandArchive::has_super() const {
  return _internal_has_super();
}
inline const ::TSASOS::CommandReapplyMasterArchive& ReapplyPageTemplateCommandArchive::_internal_super() const {
  const ::TSASOS::CommandReapplyMasterArchive* p = super_;
  return p != nullptr ? *p : reinterpret_cast<const ::TSASOS::CommandReapplyMasterArchive&>(
      ::TSASOS::_CommandReapplyMasterArchive_default_instance_);
}
inline const ::TSASOS::CommandReapplyMasterArchive& ReapplyPageTemplateCommandArchive::super() const {
  // @@protoc_insertion_point(field_get:TPSOS.ReapplyPageTemplateCommandArchive.super)
  return _internal_super();
}
inline void ReapplyPageTemplateCommandArchive::unsafe_arena_set_allocated_super(
    ::TSASOS::CommandReapplyMasterArchive* super) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(super_);
  }
  super_ = super;
  if (super) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:TPSOS.ReapplyPageTemplateCommandArchive.super)
}
inline ::TSASOS::CommandReapplyMasterArchive* ReapplyPageTemplateCommandArchive::release_super() {
  _has_bits_[0] &= ~0x00000001u;
  ::TSASOS::CommandReapplyMasterArchive* temp = super_;
  super_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::TSASOS::CommandReapplyMasterArchive* ReapplyPageTemplateCommandArchive::unsafe_arena_release_super() {
  // @@protoc_insertion_point(field_release:TPSOS.ReapplyPageTemplateCommandArchive.super)
  _has_bits_[0] &= ~0x00000001u;
  ::TSASOS::CommandReapplyMasterArchive* temp = super_;
  super_ = nullptr;
  return temp;
}
inline ::TSASOS::CommandReapplyMasterArchive* ReapplyPageTemplateCommandArchive::_internal_mutable_super() {
  _has_bits_[0] |= 0x00000001u;
  if (super_ == nullptr) {
    auto* p = CreateMaybeMessage<::TSASOS::CommandReapplyMasterArchive>(GetArena());
    super_ = p;
  }
  return super_;
}
inline ::TSASOS::CommandReapplyMasterArchive* ReapplyPageTemplateCommandArchive::mutable_super() {
  // @@protoc_insertion_point(field_mutable:TPSOS.ReapplyPageTemplateCommandArchive.super)
  return _internal_mutable_super();
}
inline void ReapplyPageTemplateCommandArchive::set_allocated_super(::TSASOS::CommandReapplyMasterArchive* super) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(super_);
  }
  if (super) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(super)->GetArena();
    if (message_arena != submessage_arena) {
      super = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, super, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  super_ = super;
  // @@protoc_insertion_point(field_set_allocated:TPSOS.ReapplyPageTemplateCommandArchive.super)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace TPSOS

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_TPCommandArchives_2esos_2eproto
